oneOf:
  - $ref: ./actions/load.yaml
  - $ref: ./actions/unload.yaml
  - $ref: ./actions/stop.yaml
  - $ref: ./actions/move.yaml
  - $ref: ./actions/handOver.yaml
  - $ref: ./actions/attachTransportEquipment.yaml
  - $ref: ./actions/detachTransportEquipment.yaml
  - $ref: ./actions/refuel.yaml
  - $ref: ./actions/break.yaml
  - $ref: ./actions/wait.yaml
  - $ref: ./actions/genericAction.yaml
  - $ref: ./actions/weigh.yaml
discriminator:
  propertyName: actionType
  mapping:
    load: ./actions/load.yaml
    unload: ./actions/unload.yaml
    stop: ./actions/stop.yaml
    move: ./actions/move.yaml
    handOver: ./actions/handOver.yaml
    attachTransportEquipment: ./actions/attachTransportEquipment.yaml
    detachTransportEquipment: ./actions/detachTransportEquipment.yaml
    refuel: ./actions/refuel.yaml
    break: ./actions/break.yaml
    wait: ./actions/wait.yaml
    genericAction: ./actions/genericAction.yaml
    weigh: ./actions/weigh.yaml
