put:
  operationId: createRoute
  responses:
    '200':
      description: The same entity
      content:
        application/json:
          schema:
            $ref: ../components/schemas/entity/route.yaml
    '400':
      description: Client error
      content:
        application/json:
          schema:
            $ref: ../components/schemas/error/clientError.yaml
    '500':
      description: Server error
      content:
        application/json:
          schema:
            $ref: ../components/schemas/error/serverError.yaml
  summary: Adds a new Route
  requestBody:
    content:
      application/json:
        schema:
          $ref: ../components/schemas/entity/route.yaml
  tags:
    - Route
  security:
    - BearerToken: []
